/**
 * Types of {@link QRCode}s that can be generated by the API.
 */
export enum QRCodePaymentReferenceType {
	/** Associated to a Payment Request */
	PAYMENT_REQUEST = "PAYMENT_REQUEST",

	/** Associated to a {@link PaymentSession} */
	PAYMENT_SESSION = "PAYMENT_SESSION"
}
